# command to run:
# docker-compose -f docker-compose-dev-hot.yml up

# This will start csps-dependencies & postgres db container with it's
# associated data volumes container and run 'npm run dev:hot'

version: '3'
services:
  dev:
    image: mgpeters/saga-weather-dev
    container_name: saga-weather-dev
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run dev
# shared volumes for development
volumes:
  node_modules:
